### ISSUE TITLE
Ubunut 17.10 thinks lambda is propritary

### ISSUE THREAD

**Issue by f-heeger** [seqan/lambda#110]
When installing the lambda (1.9.3) deb package on Ubuntu 17.10 the software manager shows that lambda is propritary:
![screenshot from 2017-12-21 18-35-01](https://user-images.githubusercontent.com/13696251/34275348-30c53b16-e69d-11e7-9076-cb7bd6b8219a.png)

**Comment by h-2** [comment]
Hm, more tricky than I thought. Seems to be a bug since 2009: https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/435183

And it is not clear whether this has been fixed by checking for the debian/copyright file or not. I have created a modified debball, can you check whether it behaves the same? [remove .txt extension]

[lambda-1.9.3-Linux-x86_64.deb.txt](https://github.com/seqan/lambda/files/1600308/lambda-1.9.3-Linux-x86_64.deb.txt)

**Comment by f-heeger** [comment]
The software center says: "Don't know how to handle 'lambda-1.9.3-Linux_x86_64.deb'"

**Comment by h-2** [comment]
Closing this since it is really old. If problems persist, please reopen.
