### ISSUE TITLE
Index Sizing and Extension Modes

### ISSUE THREAD

**Issue by bfowle** [seqan/lambda#144]
Hello,

I'm trying to get an understanding of best practices when sizing my Lambda indexes and choosing extension modes and/or splitting indexes/input FASTA up in a smart way. I'm currently using the entire UniRef100 as an index (~126GB+) and comparing results to [UniProt BLAST](https://www.uniprot.org/blast/) web-based results.

From my understanding, with extension mode `auto` -- it chooses either `xdrop`/`fullSIMD` (or `fullSerial` if SIMD is not enabled from seqan/seqan) based on query length. From testing and comparing results to UniProt's BLAST tool, `auto` never returns any alignments for certain test cases when the input index is large enough. I have a smaller UniRef100 subset (~3MB) and alignments are found when using `auto` as the extension mode. I _do_ however, get results exactly like that on UniProt's site, with `fullSerial` extension mode -- which may not be ideal if there's queries >100 bps that `xdrop` may be better suited for.

Looking at the e-values that come back, these seem to be very different than that on the UniProt tool. (e.g. UniProt = 1.5, Lambda = 1e-106).

My main questions are:
- should I be splitting the index into smaller chunks than the current sized one and align to multiple databases and would this help extension mode `auto` to work?
- should I be splitting the input FASTA into <100, >=100 query length ones and running either `auto` or `xdrop`/`fullSerial` manually to get proper results?
- are the e-values being calculated a much different way than the UniProt tool and/or would splitting the indexes into smaller chunks help with this?

Cheers~

**Comment by h-2** [comment]
Dear Brett,

I think there are two things at play here:

1. Something many people don't realise is that the e-value is a length-normalised score, i.e. one and the same alignment between a query sequence and a subject sequence will have a different e-value depending on how many other sequences are in the database (because the chance of a random hit is higher in a larger database, scores for the same alignment are considered less significant). This means cutting databases into smaller chunks can have a very strong influence on the scores you see. It is one of the reasons I prefer using the bits-score which is "e-value but independent of sequence/database size". Can you compare those and see if you get different results for UniProt and lambda?
2. Slightly different scores for `xdrop` VS `fullSIMD` are expected, because the methodology is very different, but different scores between `fullSerial` VS `fullSIMD `are definitely a bug. We have recently fixed some bugs in this area in the lambda3-branch. In any case, there should be little reason to use fullSerial.

Whether or not the query sequences should be split into different sets depending on the lengths, really depends on the use-case. If you only have a few long sequences you can also just manually select `fullSIMD` (or the other way around). If you routinely perform analysis on both long and short sequences, it might be better split up the files.

**Comment by bfowle** [comment]
Hi, I understand the e-value score is based on the number of sequences in the index; I think maybe comparing that with the UniProt results was a red-herring. However, if you say the `fullSIMD` vs. `fullSerial` results being a bug is true, then I should be using a newer version of lambda (3?). I have attempted to build this locally recently but failed to do so. Is there a specific tag I should be building lambda3 with? Or do you see cutting a new version of the 1.9.x branch with any of these recent bug-fixes?
Thanks~

**Comment by h-2** [comment]
>  However, if you say the fullSIMD vs. fullSerial results being a bug is true,

Well, fullSIMD should be correct, only fullSerial was affected by a bug that we know of.

> then should I be using a newer version of lambda (3?). I have attempted to build this locally recently but failed to do so.

Lambda3 is currently a fast-moving target and still quite unstable. We expect to have a more stable version in early January.

> Or do you see cutting a new version of the 1.9.x branch with any of these recent bug-fixes?

We might, but I can't promise it right now.

**Comment by bfowle** [comment]
I see. The symptoms I've been seeing are hiding results from `auto` (and `fullSIMD` being picked <100bps) mode.

For example:
IndexA (3MB) shows accession ABC123 with 100.0 pident
IndexB (200+GB) does not show accession ABC123 at all
(IndexA is a subset of IndexB and both have this accession in their index.)

I have `-e 100` set and have tried various seeding/filtering options; the only time I saw ABC123 come up in a result with IndexB, it was when `fullSerial` algo was being used.

I will say, with `fullSerial`, there were a lot of "0.0" evalues in the results -- is this the bug you were referring to for that mode?

**Comment by h-2** [comment]
Dear Brett,

sorry for the long delay! I have recently committed multiple patches to the master branch, these concern especially problem of the `fullSerial` mode. 
I'd love to hear if they make results consistent for you.

Thanks.
Hannes

P.S: We will likely make a 2.0.1 release that contains these fixes.

**Comment by bfowle** [comment]
Hi @h-2, I built from the latest `master` and tested with some examples (settings: `-e 100 -n 10`).

Lambda version | Extension Mode | Results
--------------------- | ---------------------- | ----------
1.9.5                  | auto                     | 0
1.9.5                  | fullSerial              | 10
master               | auto                     | 0
master               | fullSerial              | 0

So looks like these results from before with extension mode set to `fullSerial` were not supposed to show up? However, these 10 results show up when searching on the UniProt site (default settings... `blastx` / UniRef100 / e-threshold: 100).

I'd like to run with extension mode set to `auto`, especially on short reads against large indexes. I opened the issue mainly because I saw results that were consistent with comparing to the UniProt site and attempting different settings on lambda until they showed up as well; hoping it was a possible issue with the `auto`/`fullSIMD` mode.

Comparing the e-values on the results I got from 1.9.5 and the ones on UniProt; they're extremely different:
- UniProt results: **1.5**
- lambda 1.9.5 [fullSerial]: **1e-106**

**Comment by h-2** [comment]
Dear Brett,

from my perspective there was clearly an error in fullSerial mode that we fixed.

> Comparing the e-values on the results I got from 1.9.5 and the ones on UniProt; they're extremely different:

Yes, fullSerial mode had a bug in the evalue computation which is why evalues were close to 0 although they shouldn't have been.

If you search only for the respective sequence(s) locally and run lambda with `-v 2`, do hits appear as "failing the e-value test" ?

If yes, you could try to recompile lambda and change the maximum allowed e-value here:
https://github.com/seqan/lambda/blob/master/src/search_options.hpp#L248
to be something like 100'000 and then try the search again with `-e 100000`.

It is quite possible that the e-value for identical alignments would not be identical between programs (although the difference is usually quite small). I compared this a while ago and found that none of the local alignment tools (including lambda) could replicate Blast exactly and concluded the function used inside Blast is not as documented in the literature (many of the tools were consistent between each other).
If the bit-score of respective hits are identical but the e-values are not, this is likely the reason.

Additionally, newer versions of Blast often activate "compositional score matrix adjustments" [1] automatically that sometimes alter the e-value and also the bit-score. You can check if this is the case by comparing the bit-scores, if they are different (although the alignment is the same), this is likely the case.
I chose against implementing support for "compositional score matrix adjustments" because they are very complex [2]  and usually make only a small difference. 

[1] https://www.ncbi.nlm.nih.gov/pubmed/16218944
[2] BLAST's code for only performing this adjustment is over 3700 lines of code (for comparison, Lambda's entire code is 5700 lines of code). Additionally, thousands of pre-computed values would have to be imported -> it's a mess.

**Comment by bfowle** [comment]
Thank you for the very detailed information; it's incredibly informative!

> If you search only for the respective sequence(s) locally and run lambda with -v 2, do hits appear as "failing the e-value test" ?

Here's the results testing with `fullSerial` before/after the latest fixes:

Before:
```
   HITS                              Remaining
   after Seeding                     24403
 - failed pre-extend test     2329 = 22074
 - failed %-identity test        0 = 22074
 - failed e-value test       17282 =  4792
 - duplicates                    0 =  4792
 - abundant                   4782 =    10
```

After:
```
   HITS                              Remaining
   after Seeding                     24403
 - failed pre-extend test     2329 = 22074
 - failed %-identity test        0 = 22074
 - failed e-value test       22074 =     0
 - duplicates                    0 =     0
 - abundant                      0 =     0
```
```

So yes, the e-value test is where these are now being filtered (properly).

I agree with lambda's approach, and 99.999% of the time it's been solid for use cases we see. So thanks again for that. This particular case will likely not be normal; running a <30bps sequence should probably be done with an SRA instead.

I was also very interested in being able to test running with the `-e` setting higher; for example, NCBI's online tool allows 1000 as an option. Being able to tweak this for larger-sized indexes may be helpful in the future for us as some indexes (e.g. UR100) will only be getting bigger with time.

Cheers~

**Comment by bfowle** [comment]
@h-2 -- one quick followup. I tested with e-value allowed up to 100,000 as suggested. I ran with extension mode `auto` and was able to get all the results that show on UniProt's site with lambda as well. Again, the e-values are much different:
- UniProt: 1.5
- lambda2 [with e-value = 100,000]: 36,791; 62,755; 81,961; etc.
Cheers~

**Comment by h-2** [comment]
Thank you for following up on this! We should definitely remove the upper bound for e-values.

One more thing, can you post one of the alignments produced in Blast Pairwise report format (`.m0`) from lambda and from Uniprot? And if you can provide us with the file, we could also double-check that it isn't really a bug on our side somewhere.

**Comment by bfowle** [comment]
Test input:
```
>Foo
AAGGAGACACTCAAGAGGCTCGGACTAGATT
```

Database index: all of UniRef100 (sans UniParc) -- approx. 126GB, several months old.

---

lambda2 binary built from `master` with:

```
Build configuration
-- LAMBDA version is: 2.0.0
-- The following options are selected for the build:
     LAMBDA_FASTBUILD                OFF
     LAMBDA_LINGAPS_OPT              OFF
     LAMBDA_LONG_PROTEIN_SUBJ_SEQS   OFF
     LAMBDA_MMAPPED_DB               ON
     LAMBDA_NATIVE_BUILD             ON
     LAMBDA_MULTIOPT_BUILD           OFF
     LAMBDA_STATIC_BUILD             ON
```

`searchp` run with flags: `-e 100000 -n 10`

---

Tabular Output:

```
Foo    UniRef100_E7C196        100.00  10      0       0       1       30      101     110     36791   23.5
Foo    UniRef100_T1B7E5        90.00   10      1       0       1       30      145     154     62755   22.7
Foo    UniRef100_A0A1F5DQB1    90.00   10      1       0       1       30      602     611     81961   22.3
Foo    UniRef100_A0A2Z2MAV0    90.00   10      1       0       1       30      599     608     81961   22.3
Foo    UniRef100_Q9ZQL1        90.00   10      1       0       1       30      38      47      81961   22.3
Foo    UniRef100_A0A1I1FB39    90.00   10      1       0       1       30      269     278     81961   22.3
```

Pairwise Output:

```
Query= Foo
                                                                                                                                                     
Length=31
                                                                   Score     E
Sequences producing significant alignments:                       (Bits)  Value

UniRef100_E7C196                                                     23  4e+04
UniRef100_T1B7E5                                                     22  6e+04
UniRef100_A0A1F5DQB1                                                 22  8e+04
UniRef100_A0A2Z2MAV0                                                 22  8e+04
UniRef100_Q9ZQL1                                                     22  8e+04
UniRef100_A0A1I1FB39                                                 22  8e+04

ALIGNMENTS
> UniRef100_E7C196
Length=327

 Score =  23.5 bits (49), Expect =  4e+04
 Identities = 10/10 (100%), Positives = 10/10 (100%), Gaps = 0/10 (0%)
 Frame = +1

Query  1    KETLKRLGLD  30
            KETLKRLGLD
Sbjct  101  KETLKRLGLD  110

> UniRef100_T1B7E5                                                                                                                           [44/2866]
Length=158

 Score =  22.7 bits (47), Expect =  6e+04
 Identities = 9/10 (90%), Positives = 10/10 (100%), Gaps = 0/10 (0%)
 Frame = +1

Query  1    KETLKRLGLD  30
            KET+KRLGLD
Sbjct  145  KETIKRLGLD  154


> UniRef100_A0A1F5DQB1
Length=622

 Score =  22.3 bits (46), Expect =  8e+04
 Identities = 9/10 (90%), Positives = 10/10 (100%), Gaps = 0/10 (0%)
 Frame = +1

Query  1    KETLKRLGLD  30
            KETL+RLGLD
Sbjct  602  KETLRRLGLD  611


> UniRef100_A0A2Z2MAV0
Length=621

 Score =  22.3 bits (46), Expect =  8e+04
 Identities = 9/10 (90%), Positives = 10/10 (100%), Gaps = 0/10 (0%)
 Frame = +1

Query  1    KETLKRLGLD  30
            KETLK+LGLD
Sbjct  599  KETLKKLGLD  608

> UniRef100_Q9ZQL1                                                                                                                            [8/2866]
Length=263

 Score =  22.3 bits (46), Expect =  8e+04
 Identities = 9/10 (90%), Positives = 10/10 (100%), Gaps = 0/10 (0%)
 Frame = +1

Query  1   KETLKRLGLD  30
           KETLKR+GLD
Sbjct  38  KETLKRVGLD  47


> UniRef100_A0A1I1FB39
Length=478

 Score =  22.3 bits (46), Expect =  8e+04
 Identities = 9/10 (90%), Positives = 10/10 (100%), Gaps = 0/10 (0%)
 Frame = +1

Query  1    KETLKRLGLD  30
            KETLK+LGLD
Sbjct  269  KETLKKLGLD  278

Lambda     K      H
   0.267   0.0410   0.1400

Gapped
Lambda     K      H
   0.267   0.0410   0.1400

Effective search space used: 1337176148756
  Database: /dev/shm/uniref100.lambda/
  Number of letters in database: 43134714476
  Number of sequences in database:  123297772

Matrix: BLOSUM62
Gap Penalties: Existence: 11, Extension: 1
```

UniProt Alignments:

Cluster Member | E-value | Score | Pident | Hit length
--- | --- | --- | --- | ---
UniRef100_E7C196 | 1.5 | 72 | 100.0% | 327
UniRef100_A0A2E7K3U3 | 12.0 | 66 | 90.0% | 686
UniRef100_A0A524L7G2  | 12.0 | 66 | 90.0% | 621

...etc.
