### ISSUE TITLE
.fna files

### ISSUE THREAD

**Issue by hildebra** [seqan/lambda#223]
Hey,
I came across the following input related problem:
"
terminate called after throwing an instance of 'sharg::validation_error'
  what():  Validation failed for option -d/--database: Expected one of the following valid extensions: [fa, fq, fasta, fastq, fa.gz, fq.gz, fasta.gz, fastq.gz]! Got fna instead!
MG.sh: line 17: 17139 Aborted                 lambda3 mkindexn -t 12 -d TIGR00539.fna
"

While I realize that normally this could be solved with a "mv", I am working with an array of reference databases shared for many users in an HPC environment. Would there be an easy way to override the ".fa" requirement?
Thanks,
Falk

**Comment by SGSSGene** [comment]
Hi Falk

The list of extension is hardcoded and there is no way to override it from the outside. (` std::vector<std::string> extensions{"fa", "fq", "fasta", "fastq"};`). But you could edit the code and recompile by adding "fna".

See:
https://github.com/seqan/lambda/blob/d995cb5d99990943622bb8149ba52cdaf9c0eb76/src/search_options.hpp#L157
and
https://github.com/seqan/lambda/blob/d995cb5d99990943622bb8149ba52cdaf9c0eb76/src/mkindex_options.hpp#L95


Other Idea: Instead of running 'mv' you could also use `ln -s` to create a sym link with `fa` extension. (But this might also not be an option for your HPC environment).

**Comment by hildebra** [comment]
Thanks Simon,
I followed the ln -s route, but just a bit of a shame to have these hard limitations.
Thanks in any case for lambda3, really love the speed!
cheers,
Falk

**Comment by sarahet** [comment]
Hi Falk,

Great to hear that you are happy with the new version of lambda. We will think about adding ```fna``` as a valid file extension in our next release of lambda3. We will let you know if it becomes available in the nearer future.

Sara

**Comment by sarahet** [comment]
This has been addressed by #224 so you should be able to run lambda3 with ```fna``` file extension with the latest version of the lambda3 branch.
