### ISSUE TITLE
std::bad_alloc exception in lambda_indexer 1.9.2 when indexing large database

### ISSUE THREAD

**Issue by YXAndyYX** [seqan/lambda#90]
Dear Hannes and other lambda maintainers,

I'm getting an error running the following command:

`lambda_indexer -p blastn -d ~/databases/nt.fa`

The program output is the following:

~~~
Loading Subject Sequences and Ids... done.
Dumping Subj Ids... done.
Dumping unreduced Subj Sequences... done.
Generating       0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
 (1) SuffixArray |~/software/lambda/include/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::bad_alloc: std::bad_alloc)

stack trace:
  0                      [0x41afa9]
  1                      [0x41c468]
  2                      [0x64b736]
  3                      [0x64b781]
  4                      [0x64bc99]
  5                      [0x64cc19]
  6                      [0x45d9d5]
  7                      [0x5eaf16]
  8                      [0x4084f2]
  9                      [0x6afe29]
 10                      [0x40d309]

Aborted
~~~

The lambda_indexer was compiled a few days ago with the newest available seqan version, but produced the same error with the seqan version that is linked as a submodule in the repo.
It gives the following version information:

~~~
VERSION
    Last update: Feb  1 2017
    lambda_indexer version: 1.9.2
    SeqAn version: 2.4.0
~~~

I'm assuming that the error might either be due to the size of the database (~ 130 GB uncompressed) or maybe the format of our sequence name/annotation lines, which are not quite like the original NCBI ones.
They include the taxonomic lineage of the sequence and look like this:

`>gi|31341369|ref|NM_176670.2|_Bos_taurus_ATP_synthase,_H+_transporting,_mitochondrial_F1_complex,_delta_subunit_(ATP5D),_mRNA||gi|109|emb|X17019.1|_B.taurus_mRNA_for_delta_subunit_of_ATP_synthase||109,31341369|species:9913:Bos_taurus|genus:9903:Bos|subfamily:27592:Bovinae|family:9895:Bovidae|infraorder:35500:Pecora|suborder:9845:Ruminantia|no_rank:91561:Cetartiodactyla|superorder:314145:Laurasiatheria|no_rank:1437010:Boreoeutheria|no_rank:9347:Eutheria|no_rank:32525:Theria|class:40674:Mammalia|no_rank:32524:Amniota|no_rank:32523:Tetrapoda|no_rank:1338369:Dipnotetrapodomorpha|no_rank:8287:Sarcopterygii|no_rank:117571:Euteleostomi|no_rank:117570:Teleostomi|no_rank:7776:Gnathostomata|no_rank:7742:Vertebrata|subphylum:89593:Craniata|phylum:7711:Chordata|no_rank:33511:Deuterostomia|no_rank:33213:Bilateria|no_rank:6072:Eumetazoa|kingdom:33208:Metazoa|no_rank:33154:Opisthokonta|superkingdom:2759:Eukaryota|no_rank:131567:cellular_organisms|no_rank:1:root`

Any help that would enable me to index and use my database would be much appreciated.
If I any more information is needed, I will gladly provide it if I can.

Many thanks in advance
Andy

**Comment by h-2** [comment]
Dear Andy,

thanks for your report! You are right, this is most likely an out-of-memory problem. There are different indexing algorithms with different requirements (but same outcome):
  * `--algorithm radixsort` (the default)
    * memory usage of ~ 10x sequence size
    * no hard disk usage
    * progress indicator
    * full parallelization → fastest
  * `--algorithm skew7ext`
    * memory usage of ~ 2x sequence size
    * disk usage of 30x sequence size in the current directory or in directory specified by `--tmp-dir`
    * no progress indicator
    * no parallelization, slower than above

Note that "sequence size" refers to the total size of you sequence data, usually without the headers so if your file is 130GB and half of that are headers (don't know if this is true for your file), your requirement for radixsort are ~650GB RAM. The second method requires much less RAM, but even more disk space and it is also slower, but maybe worth a try if you don't have the RAM.

**Please note that this memory is only required once during indexing and the search usually only needs ~2x you sequence size in RAM.**

> or maybe the format of our sequence name/annotation lines, which are not quite like the original NCBI ones.

This is independent of the error, but lambda will not yet extract the correct IDs because they are encoded in GI (not supported and won't be) and refseq accession (not yet supported, but will be).
So the taxonomic features of lambda will not yet work on your data. However you seem to have this information encoded in the header already so you can do the analysis independent of Lambda.

I hope these comments could help you. I am aware that the initial indexing requirements are quite severe and I want to change this in the future, but currently some other matters are more pressing. I will work on support for refseq accession IDs for the next release.

Best regards,
Hannes

**Comment by YXAndyYX** [comment]
Dear Hannes,

I forgot to mention that the command was run on a server with 1 TB of RAM without any resource management system in place.
So I assume it's not per se an out of memory error.
I haven't tried using another sorting algorithm yet but I will do that tomorrow and then report on the outcome.

I also haven't looked into lambda's own taxonomy handling features yet.
The database is annotated like that because of historical reasons and for compatibility with other mappers.
The other in-house databases mentioned above also don't include GIs anymore but follow the same annotation scheme pretty closely.
I just wanted to attach the annotation info because I've encountered other mappers having problems with these due to length or formatting before and it's good to know that lambda seemingly doesn't have problem with that scheme. :)

Thanks for the swift reply, I will keep you updated.

Best regards,
Andy

**Comment by h-2** [comment]
> I forgot to mention that the command was run on a server with 1 TB of RAM without any resource management system in place.
> So I assume it's not per se an out of memory error.

I also just saw that you are indexing in BLASTN mode. In this case the index is bigger, because it assumes that the sequences can be longer than for protein so it's more of a factor 18x than 10x. I would still assume its out-of-memory and than the other construction algorithm would work better, however it would use an exceptional amount of disk space, I don't know if you have that available. And I expect the run-time to be multiple days :expressionless: 

> I also haven't looked into lambda's own taxonomy handling features yet.

Ah, ok, they are also quite experimental still :grinning: 

> I just wanted to attach the annotation info because I've encountered other mappers having problems with these due to length or formatting before and it's good to know that lambda seemingly doesn't have problem with that scheme. :)

Long IDs are not a problem. It automatically truncates at first whitespace, but if there is none, it will just include the full ID.

> Thanks for the swift reply, I will keep you updated.

No problem and thanks for keeping me up date.

PS: I want to pre-compute the required amount of RAM in the future so that Lambda will immediately tell the user if it expects to run out-of-mem later on.

**Comment by YXAndyYX** [comment]
> PS: I want to pre-compute the required amount of RAM in the future so that Lambda will immediately tell the user if it expects to run out-of-mem later on.

I talked about that with a colleague a few days ago as well. It would be a nice feature. A worst case estimation would be enough already I think. :)

Apart from that, I ran

`/usr/bin/time -v ~/software/lambda_1.9.2/lambda_indexer -p blastn -d ~/databases/nt.fa -a mergesort`

today with the following output

~~~
WARNING: mergesort tag is deprecated and superseded by "radixsort", please adapt your program calls.
Loading Subject Sequences and Ids... done.
Dumping Subj Ids... done.
Dumping unreduced Subj Sequences... done.
Generating       0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
 (1) SuffixArray |~/software/lambda/include/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::bad_alloc: std::bad_alloc)

stack trace:
  0                      [0x41afa9]
  1                      [0x41c468]
  2                      [0x64b736]
  3                      [0x64b781]
  4                      [0x64bc99]
  5                      [0x64cc19]
  6                      [0x45d9d5]
  7                      [0x5eaf16]
  8                      [0x4084f2]
  9                      [0x6afe29]
 10                      [0x40d309]

Command terminated by signal 6
        Command being timed: "~/software/lambda_1.9.2/lambda_indexer -p blastn -d ~/databases/nt.fa -a mergesort"
        User time (seconds): 1123.25
        System time (seconds): 615.12
        Percent of CPU this job got: 44%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:05:47
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 252193656
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 141389785
        Voluntary context switches: 4446053
        Involuntary context switches: 1607918
        Swaps: 0
        File system inputs: 664
        File system outputs: 275328048
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
~~~

The time output shows that the process did not use up more than roughly 250 GB of RAM during the execution while no more than 400 GB were occupied overall (including processes of other users etc.).
So there was plenty of room upwards.

Do you have any further ideas regarding this?
I'd love to use lambda but it doesn't seem to want to cooperate. :stuck_out_tongue: 

Best regards,
Andy

**Comment by h-2** [comment]
> /usr/bin/time -v ~/software/lambda_1.9.2/lambda_indexer -p blastn -d ~/databases/nt.fa -a mergesort

mergesort is not better than radix, it is actuall even worse. The one with lower RAM consumption is `skew7ext`. Can you try that one?

> The time output shows that the process did not use up more than roughly 250 GB of RAM during the execution while no more than 400 GB were occupied overall 

In this case I think it could be that lambda actually tells the operating system "give me 1.2TB of RAM" and the OS immediately responds with "I don't have it, die!" which results in the `bad_alloc` exception. ¹ But Lambda never actually used more than 250GB because it didn't get what it wanted... 

> I'd love to use lambda but it doesn't seem to want to cooperate.

Yeah, memory is a real problem. I will work on using different index structures and better on-disk construction algorithms some time soon...

> Do you have any further ideas regarding this?

Please try with `skew7ext` that should definitely not run out of RAM, although it probably will require ~ 3TB of disk :sweat_smile: 

¹ bad_alloc means not enough RAM in 99.9% of the cases.

**Comment by YXAndyYX** [comment]
> In this case I think it could be that lambda actually tells the operating system "give me 1.2TB of RAM" and the OS immediately responds with "I don't have it, die!" which results in the bad_alloc exception. ¹ But Lambda never actually used more than 250GB because it didn't get what it wanted...

Right, never thought about the possibility of the OS preemptively killing a process without letting it "test" its limits. But it just makes sense, I guess.

I had to shift to the high performance cluster to have enough disk space and just noticed a process of you there as well, so I assume you're trying to replicate the issue at hand? Nevertheless, I'm running my indexing with `skew7ext` now and will report on the results.

**Comment by h-2** [comment]
> I had to shift to the high performance cluster to have enough disk space and just noticed a process of you there as well, so I assume you're trying to replicate the issue at hand? 

Here at FU?

I am just indexing the current nr so I can offer it for download since most lambda users search protein databases. If you manage to index the nt, please let me know a local path, then I can put it on a mirror, too!
Ideally there would be an automated index building service here :thought_balloon:

**Comment by h-2** [comment]
@YXAndyYX did it work out for you or are you still encountering problems?

**Comment by YXAndyYX** [comment]
It's still indexing, but it's past the point where it threw the exception earlier.
So unless something else comes up, I guess you can close this issue.
Thanks for your support. :)

**Comment by h-2** [comment]
@YXAndyYX I am closing this now, if you have any further questions, please re-open!
